# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import comtrade_pb2 as comtrade__pb2


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/comtrade.Greeter/SayHello',
                request_serializer=comtrade__pb2.HelloRequest.SerializeToString,
                response_deserializer=comtrade__pb2.HelloReply.FromString,
                )
        self.FastLoad = channel.unary_unary(
                '/comtrade.Greeter/FastLoad',
                request_serializer=comtrade__pb2.DatParseParam.SerializeToString,
                response_deserializer=comtrade__pb2.WaveDataReply.FromString,
                )
        self.TestFastLoad = channel.unary_unary(
                '/comtrade.Greeter/TestFastLoad',
                request_serializer=comtrade__pb2.HelloRequest.SerializeToString,
                response_deserializer=comtrade__pb2.Analog.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FastLoad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestFastLoad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=comtrade__pb2.HelloRequest.FromString,
                    response_serializer=comtrade__pb2.HelloReply.SerializeToString,
            ),
            'FastLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.FastLoad,
                    request_deserializer=comtrade__pb2.DatParseParam.FromString,
                    response_serializer=comtrade__pb2.WaveDataReply.SerializeToString,
            ),
            'TestFastLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.TestFastLoad,
                    request_deserializer=comtrade__pb2.HelloRequest.FromString,
                    response_serializer=comtrade__pb2.Analog.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'comtrade.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/comtrade.Greeter/SayHello',
            comtrade__pb2.HelloRequest.SerializeToString,
            comtrade__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FastLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/comtrade.Greeter/FastLoad',
            comtrade__pb2.DatParseParam.SerializeToString,
            comtrade__pb2.WaveDataReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestFastLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/comtrade.Greeter/TestFastLoad',
            comtrade__pb2.HelloRequest.SerializeToString,
            comtrade__pb2.Analog.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
